# source was taken from rust.git 05d5fcaa5ba0c385e1dc97037c89fae437634fc3
# duration interface changed incompatibly after that

[package]
name = "test"
version = "0.1.0"
authors = []

[lib]
name = "test"
path = "lib.rs"
