[package]
name = "radeco"
version = "0.1.0"
authors = [
	"David Kreuter <dkreuter@gmail.com>",
	"Sushant Dinesh <sushant.dinesh94@gmail.com>"
]

[dependencies]
regex = "*"
petgraph = "*"
num = "*"
r2pipe = "*"
rustc-serialize = "*"
