[package]
name = "radeco"
version = "0.1.0"
authors = [
	"David Kreuter <dkreuter@gmail.com>",
	"Sushant Dinesh <sushant.dinesh94@gmail.com>"
]

[dependencies.rustc-data-structures]
doc = false
path = "src/rustc_data_structures"

[dependencies]
regex = "*"
petgraph = "*"
num = "*"
r2pipe = "*"
rustc-serialize = "*"

[[bin]]
doc = false
name = "radeco"
