[package]
name = "radeco-lib"
version = "0.1.0"
authors = [
	"David Kreuter <dkreuter@gmail.com>",
	"Sushant Dinesh <sushant.dinesh94@gmail.com>"
]

[lib]
path = "src/lib.rs"

[features]
trace_log = []
default = []

[dependencies]
regex = "*"
petgraph = "*"
num = "*"
rustc-serialize = "*"
log = "*"

[dependencies.clippy]
clippy="*"

[dependencies.r2pipe]
git = "https://github.com/radare/r2pipe.rs"

[dependencies.esil]
path = "../esil-rs"
