[package]
name = "radeco-lib"
version = "0.1.0"
authors = [
	"David Kreuter <dkreuter@gmail.com>",
	"Sushant Dinesh <sushant.dinesh94@gmail.com>"
]

[dependencies]
num = "*"
petgraph = "*"
r2pipe = "*"
regex = "*"
rustc-serialize = "*"

iron = "*"
mount = "*"
staticfile = "*"
